name: 构建Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good
          pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.33

      - name: 创建buildozer.spec文件
        run: |
          cat > buildozer.spec << EOF
          [app]
          title = 星妍AI
          package.name = xingyai
          package.domain = org.henrycheng
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas,ttf,db
          version = 0.1
          requirements = python3,kivy,pillow,requests
          orientation = portrait
          osx.python_version = 3
          osx.kivy_version = 2.1.0
          fullscreen = 0
          android.permissions = CAMERA,INTERNET,WRITE_EXTERNAL_STORAGE
          android.api = 30
          android.minapi = 21
          android.ndk = 23b
          android.sdk = 30
          android.accept_sdk_license = True
          android.arch = arm64-v8a
          
          [buildozer]
          log_level = 2
          warn_on_root = 1
          EOF

      - name: 构建APK
        run: |
          buildozer android debug

      - name: 上传APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: bin/*.apk