name: 构建Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-8-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo6 \
            cmake \
            libffi-dev \
            libssl-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev
          pip install --upgrade pip
          pip install buildozer==1.4.0
          pip install cython==0.29.33

      - name: 显示项目结构
        run: |
          ls -la
          find . -type f -name "*.py" | sort

      - name: 创建buildozer.spec文件
        run: |
          cat > buildozer.spec << EOF
          [app]
          title = 星妍AI
          package.name = xingyai
          package.domain = org.henrycheng
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas,ttf,db
          version = 0.1
          requirements = python3,kivy==2.1.0,pillow,requests
          orientation = portrait
          osx.python_version = 3
          osx.kivy_version = 2.1.0
          fullscreen = 0
          android.permissions = CAMERA,INTERNET,WRITE_EXTERNAL_STORAGE
          android.api = 30
          android.minapi = 21
          android.ndk = 27.2.12479018
          android.accept_sdk_license = True
          android.archs = arm64-v8a
          
          [buildozer]
          log_level = 2
          warn_on_root = 1
          EOF

      - name: 构建APK
        run: |
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/27.2.12479018
          export ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/27.2.12479018
          buildozer -v android debug
          
      - name: 检查构建结果
        run: |
          ls -la bin/ || echo "bin目录不存在"
          
      - name: 上传APK
        uses: actions/upload-artifact@master
        with:
          name: app-debug
          path: bin/*.apk